import { ModEntry, ModEntryLocal, ModEntryServer, NPDatabase } from './types';
export declare class ModDB {
    url: string;
    active: boolean;
    private static databasesLoaded;
    static databases: Record<string, ModDB>;
    static modRecord: Record<string, ModEntryServer[]>;
    private static testingOptInModIds;
    static addDatabase(db: ModDB): void;
    static loadDatabases(force?: boolean): void;
    static repoURLToFileName(url: string): string;
    static minifyRepoURL(url: string): string;
    static expandRepoURL(url: string): string;
    static saveDatabases(): void;
    static loadAllMods(prefferCache?: boolean): Promise<void>;
    static getHighestVersionMod<T extends ModEntry>(mods: T[]): T;
    static getLocalModOrigins(id: string): Promise<ModEntryServer[]>;
    static resolveLocalModOrigin(mod: ModEntryLocal): Promise<void>;
    static isModTestingOptIn(modId: string): boolean;
    static setModTestingOptInStatus(modId: string, status: boolean): void;
    private static isDatabaseTesting;
    static removeModDuplicatesAndResolveTesting(modsRecord: Record<string, ModEntryServer[]>): Record<string, ModEntryServer>;
    name: string;
    database: NPDatabase;
    modRecord: Record<string, ModEntryServer>;
    constructor(url: string, active?: boolean, prepare?: boolean);
    isUrlValid(): Promise<boolean>;
    private createModEntriesFromDatabase;
    getMods(callback: (mods: ModEntryServer[]) => void): Promise<void>;
}
