name: Build check

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: latest

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: 'pnpm'

            - name: Install node dependencies
              run: pnpm install

            - name: Compile
              run: pnpm run start
