name: Build check

on:
    workflow_dispatch:
    push:
        branches:
          - main


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - uses: actions/setup-node@v4

            - name: Compile
              run: npm install; npm run start
